os: linux
dist: trusty
sudo: false
language: python
cache: pip

branches:
  only:
  - master
  - v2

before_install:
  - "pip install pipenv --upgrade"

install:
  - "pipenv install --dev"

script:
  - "pipenv run make build"

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6

notifications:
  email:
    on_success: never
